"use client";

import * as React from "react";

/**
 * useSarvamRolling — near-live multilingual transcription via Sarvam REST.
 *
 * Sarvam's sync REST caps at 30s of audio, so we CANNOT send a growing
 * cumulative blob (that's the Whisper path). Instead we send NON-OVERLAPPING
 * sequential WINDOWS: every `intervalMs`, flush a decodable webm block =
 *   block 0:  chunks[0 .. end]                 (already contains the header)
 *   block N:  [header chunk] + chunks[start .. end]   (header prepended so
 *             the window is independently decodable — MediaRecorder writes
 *             the webm init segment only in the first chunk)
 *
 * Each block is run through Sarvam transcribe (original script) AND translate
 * (English) server-side; we stitch the results. Because blocks are bounded
 * and sequential there is no 30s ceiling on total length and no batch API.
 *
 * Caveat: blocks 1+ carry a ~250ms header-chunk prefix (start-of-recording
 * audio), which is almost always silence/partial and contributes little; a
 * minor source of stitch noise, acceptable for a near-live panel + an
 * English note generated by the LLM. (True word-by-word streaming would use
 * a WS relay — deferred.)
 *
 * Decoupled from the canonical: this drives the LIVE panel and accumulates a
 * best-effort original+English transcript that the submit flow uses for
 * non-English encounters. English encounters ignore this (Deepgram path).
 */

export type SarvamBlock = {
  block_idx: number;
  original: string | null;
  english: string | null;
  language_code: string | null;
  latency_ms: number;
  received_at: number;
};

export type SarvamRollingState = "idle" | "running" | "in_flight" | "error" | "stopped";

type Options = {
  slug: string;
  enabled: boolean;
  encounterId?: string;
  intervalMs?: number;
  onBlock?: (b: SarvamBlock) => void;
  onError?: (e: Error) => void;
};

export function useSarvamRolling(opts: Options) {
  const intervalMs = opts.intervalMs ?? 10_000;
  const [state, setState] = React.useState<SarvamRollingState>("idle");
  const [original, setOriginal] = React.useState("");   // accumulated original-language
  const [english, setEnglish] = React.useState("");     // accumulated English
  const [language, setLanguage] = React.useState<string | null>(null);
  const [latest, setLatest] = React.useState<SarvamBlock | null>(null);
  const [error, setError] = React.useState<string | null>(null);

  const chunksRef = React.useRef<Blob[]>([]);
  const headerRef = React.useRef<Blob | null>(null);
  const mimeRef = React.useRef<string>("audio/webm");
  const nextIdxRef = React.useRef(0);
  const blockIdxRef = React.useRef(0);
  const inFlightRef = React.useRef(false);
  const optsRef = React.useRef(opts);
  React.useEffect(() => { optsRef.current = opts; }, [opts]);

  const sendChunk = React.useCallback((chunk: Blob) => {
    if (!chunk || chunk.size === 0) return;
    if (chunksRef.current.length === 0) headerRef.current = chunk; // first chunk = webm init segment
    chunksRef.current.push(chunk);
    if (chunk.type) mimeRef.current = chunk.type;
  }, []);

  const flush = React.useCallback(async () => {
    if (inFlightRef.current) return;
    const all = chunksRef.current;
    const start = nextIdxRef.current;
    const end = all.length;
    if (end === start) return; // no new chunks

    inFlightRef.current = true;
    setState("in_flight");
    const idx = ++blockIdxRef.current;

    // Build a decodable window. Block 0 already has the header at index 0.
    const parts =
      start === 0
        ? all.slice(0, end)
        : headerRef.current
          ? [headerRef.current, ...all.slice(start, end)]
          : all.slice(start, end);
    const blob = new Blob(parts, { type: mimeRef.current });

    try {
      const form = new FormData();
      form.append("audio", blob, `sarvam_block_${idx}.webm`);
      form.append("block_idx", String(idx));
      if (optsRef.current.encounterId) form.append("encounter_id", optsRef.current.encounterId);

      const res = await fetch(
        `/${optsRef.current.slug}/api/transcribe/sarvam-live`,
        { method: "POST", body: form, cache: "no-store" },
      );
      if (!res.ok) {
        const t = await res.text().catch(() => "");
        throw new Error(`http_${res.status}: ${t.slice(0, 120)}`);
      }
      const json = (await res.json()) as {
        original?: string | null;
        english?: string | null;
        language_code?: string | null;
        latency_ms?: number;
      };
      // Success — advance the watermark so blocks stay non-overlapping.
      nextIdxRef.current = end;
      const block: SarvamBlock = {
        block_idx: idx,
        original: (json.original ?? null),
        english: (json.english ?? null),
        language_code: json.language_code ?? null,
        latency_ms: json.latency_ms ?? 0,
        received_at: Date.now(),
      };
      if (block.original) setOriginal((p) => (p ? `${p} ${block.original}` : block.original!).trim());
      if (block.english) setEnglish((p) => (p ? `${p} ${block.english}` : block.english!).trim());
      if (block.language_code) setLanguage(block.language_code);
      setLatest(block);
      setState("running");
      setError(null);
      optsRef.current.onBlock?.(block);
    } catch (e) {
      // Failure: do NOT advance the watermark — retry this window next tick.
      const msg = e instanceof Error ? e.message : String(e);
      setError(msg);
      setState("error");
      optsRef.current.onError?.(new Error(msg));
    } finally {
      inFlightRef.current = false;
    }
  }, []);

  React.useEffect(() => {
    if (!opts.enabled) { setState("stopped"); return; }
    setState("running");
    const id = window.setInterval(() => { void flush(); }, intervalMs);
    return () => {
      window.clearInterval(id);
      void flush(); // final tail flush
    };
  }, [opts.enabled, intervalMs, flush]);

  return { state, original, english, language, latest, error, sendChunk, flushNow: flush };
}
