/**
 * GUARD — the files outside lib/room-access/ that may still name a room-data table in SQL, each PINNED to its current count of mentions (a new query in one of them fails the gate) and given the reason it
 * does not serve an MCP / admin / bearer reader. Everything that serves a caller goes through lib/room-access/.
 */
export const ALLOWLIST: Record<string, { max: number; why: string }> = {
  "app/[slug]/api/encounters/[id]/finalize-upload/route.ts": { max: 1, why: "doctor-PWA encounter finalise (its own encounter run row); not room data" },
  "app/api/admin/stt-lab/gold/[id]/route.ts": { max: 1, why: "STT-lab gold for ENCOUNTERS (stt_gold.encounter_id); a window has none" },
  "app/api/admin/stt-lab/gold/route.ts": { max: 2, why: "STT-lab gold candidates / per-engine WER over ENCOUNTER subjects (the candidate query is pinned to subject_type 'encounter')" },
  "app/api/bench/brain-proxy/route.ts": { max: 2, why: "recorder-device API (install-token auth): writes and reads the CURRENT recording's session, chunks and events; no MCP/admin reader" },
  "app/api/bench/chunks/route.ts": { max: 4, why: "recorder-device API (install-token auth): writes and reads the CURRENT recording's session, chunks and events; no MCP/admin reader" },
  "app/api/bench/events/route.ts": { max: 2, why: "recorder-device API (install-token auth): writes and reads the CURRENT recording's session, chunks and events; no MCP/admin reader" },
  "app/api/bench/rooms/route.ts": { max: 1, why: "recorder-device API (install-token auth): writes and reads the CURRENT recording's session, chunks and events; no MCP/admin reader" },
  "app/api/bench/sessions/active/route.ts": { max: 3, why: "recorder-device API (install-token auth): writes and reads the CURRENT recording's session, chunks and events; no MCP/admin reader" },
  "app/api/bench/upload-url/route.ts": { max: 1, why: "recorder-device API (install-token auth): mints the upload URL for the CURRENT recording's chunk" },
  "app/api/cron/kiosk-health-retention/route.ts": { max: 4, why: "retention cron: deletes old rows by age; reads nothing back to a caller" },
  "lib/admin/rooms-live.ts": { max: 4, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/attestation.ts": { max: 1, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/bench-commands.ts": { max: 5, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/bench-orphan.ts": { max: 5, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/bench-reaper.ts": { max: 3, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/bench-window.ts": { max: 5, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/brain/fuse/live.ts": { max: 1, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/emotion/enqueue.ts": { max: 3, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds before its LIMIT (n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
  "lib/encounter-windows/warehouse-attribution.ts": { max: 2, why: "warehouse-attribution / encounter-clock pipeline (GATING-owned); reads CONSULT windows to attribute encounters, serves no MCP/admin caller" },
  "lib/encounter/admin.ts": { max: 1, why: "doctor-PWA ENCOUNTER admin (runs of encounter subjects, patient pipeline view); a room window is not an encounter subject here" },
  "lib/fleet-attention.ts": { max: 7, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/jobs/kinds/diarize-window.ts": { max: 1, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/emotion-window.ts": { max: 6, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/jev-english.ts": { max: 4, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/jev-role.ts": { max: 4, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/jev-window.ts": { max: 3, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/room-window.ts": { max: 2, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/sarvam-translate.ts": { max: 1, why: "job kind: the run / window source is held-out checked by its heldOut hook at submit and at every step before pickSourceText reads the run" },
  "lib/mcp/tools/bench.ts": { max: 3, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/mcp/tools/s8.ts": { max: 2, why: "scribe_sarvam: the translate pre-check reads one run's subject_type, and usage counts Sarvam-engine runs per engine per day; Sarvam never takes room audio, so no window run exists (counts only)" },
  "lib/room-watchdog.ts": { max: 5, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/room-window-reaper.ts": { max: 2, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/rooms-live/read.ts": { max: 4, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/steward/executor.ts": { max: 2, why: "Room Steward senses and acts on the live fleet (open sessions, today); not a caller-facing reader" },
  "lib/steward/loop.ts": { max: 2, why: "Room Steward senses and acts on the live fleet (open sessions, today); not a caller-facing reader" },
  "lib/steward/sense.ts": { max: 9, why: "Room Steward senses and acts on the live fleet (open sessions, today); not a caller-facing reader" },
  "lib/stt/auto-drain.ts": { max: 8, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds, filtering the scan result in JS before it ranks/caps (no SQL LIMIT; exact n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
  "lib/stt/diarize-window.ts": { max: 4, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/stt/fanout.ts": { max: 13, why: "STT-lab fan-out of ENCOUNTER audio to engines and its run bookkeeping (lab pipeline, not a caller-facing reader of window transcripts)" },
  "lib/stt/join-only.ts": { max: 3, why: "production pipeline CHOOSER of clipless windows: leaves held-out ones out twice, through room-access blindWindowIds before its LIMIT (n_blind_excluded) and again in its own SQL by the window's OWN room_day against the BLIND_ROOM_DAYS constant (clip-join); its listing also asks grid_aligned, JOIN_MAX_MS and a session chunk, and the bench_chunk / room_day mentions are those predicates, not a reader" },
  "lib/stt/measure-job.ts": { max: 6, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds before its LIMIT (n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
  "lib/stt/room-drain.ts": { max: 21, why: "production pipeline CHOOSER (+ the join step, whose cutter refuses a held-out window from its OWN room_day before any service call or write, and fails closed on a missing day): picks its own windows, leaves held-out ones out through room-access blindWindowIds before its LIMIT (n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
  "lib/stt/scoring.ts": { max: 14, why: "STT-lab scoring of ENCOUNTER runs against gold (writes wer / cer / term recall); no caller-facing window transcript read" },
  "lib/stt/translate-bakeoff.ts": { max: 8, why: "translation bake-off over stored ENCOUNTER runs (lab script); no window subject" },
  "lib/stt/window-scoring.ts": { max: 1, why: "window scoring inside the measure job (pipeline job body); reached only from lib/stt/measure-job.ts, serves no caller" },
  "lib/transcript/repeat-runs-backfill.ts": { max: 3, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds, filtering the scan result in JS before it ranks/caps (no SQL LIMIT; exact n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
};
