/**
 * GUARD — the files outside lib/room-access/ that may still name a room-data table in SQL, each PINNED to its current count of mentions (a new query in one of them fails the gate) and given the reason it
 * does not serve an MCP / admin / bearer reader. Everything that serves a caller goes through lib/room-access/.
 */
export const ALLOWLIST: Record<string, { max: number; why: string }> = {
  "app/api/bench/brain-proxy/route.ts": { max: 2, why: "recorder-device API (install-token auth): writes and reads the CURRENT recording's session, chunks and events; no MCP/admin reader" },
  "app/api/bench/chunks/route.ts": { max: 3, why: "recorder-device API (install-token auth): writes and reads the CURRENT recording's session, chunks and events; no MCP/admin reader" },
  "app/api/bench/events/route.ts": { max: 2, why: "recorder-device API (install-token auth): writes and reads the CURRENT recording's session, chunks and events; no MCP/admin reader" },
  "app/api/bench/rooms/route.ts": { max: 1, why: "recorder-device API (install-token auth): writes and reads the CURRENT recording's session, chunks and events; no MCP/admin reader" },
  "app/api/bench/sessions/active/route.ts": { max: 2, why: "recorder-device API (install-token auth): writes and reads the CURRENT recording's session, chunks and events; no MCP/admin reader" },
  "app/api/cron/kiosk-health-retention/route.ts": { max: 4, why: "retention cron: deletes old rows by age; reads nothing back to a caller" },
  "lib/admin/rooms-live.ts": { max: 3, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/attestation.ts": { max: 1, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/bench-commands.ts": { max: 5, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/bench-orphan.ts": { max: 2, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/bench-reaper.ts": { max: 2, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/bench-window.ts": { max: 4, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/brain/fuse/live.ts": { max: 1, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/emotion/enqueue.ts": { max: 3, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds before its LIMIT (n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
  "lib/encounter-windows/occupant.ts": { max: 1, why: "warehouse-attribution / encounter-clock pipeline (GATING-owned); reads CONSULT windows to attribute encounters, serves no MCP/admin caller" },
  "lib/encounter-windows/warehouse-attribution.ts": { max: 2, why: "warehouse-attribution / encounter-clock pipeline (GATING-owned); reads CONSULT windows to attribute encounters, serves no MCP/admin caller" },
  "lib/fleet-attention.ts": { max: 4, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/jobs/kinds/diarize-window.ts": { max: 1, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/emotion-window.ts": { max: 6, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/jev-english.ts": { max: 3, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/jev-role.ts": { max: 4, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/jev-window.ts": { max: 3, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/jobs/kinds/room-window.ts": { max: 2, why: "job kind: runs only after the central heldOut hook (submit and every step); the jev kinds also drop blind windows inside the loop (K4-2)" },
  "lib/mcp/tools/bench.ts": { max: 2, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/room-watchdog.ts": { max: 3, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/room-window-reaper.ts": { max: 2, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/rooms-live/read.ts": { max: 3, why: "live-ops view bound to OPEN sessions or the current IST day by construction (no date argument can name a past held-out pair)" },
  "lib/steward/executor.ts": { max: 2, why: "Room Steward senses and acts on the live fleet (open sessions, today); not a caller-facing reader" },
  "lib/steward/loop.ts": { max: 1, why: "Room Steward senses and acts on the live fleet (open sessions, today); not a caller-facing reader" },
  "lib/steward/sense.ts": { max: 6, why: "Room Steward senses and acts on the live fleet (open sessions, today); not a caller-facing reader" },
  "lib/stt/auto-drain.ts": { max: 8, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds, filtering the scan result in JS before it ranks/caps (no SQL LIMIT; exact n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
  "lib/stt/diarize-job.ts": { max: 3, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds before its LIMIT (n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
  "lib/stt/diarize-window.ts": { max: 4, why: "production pipeline writer/reaper/planner: only closes, expires or plans rows, chooses no window for processing; MCP-submitted work is guarded by the job hook" },
  "lib/stt/join-only.ts": { max: 2, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds before its LIMIT (n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
  "lib/stt/measure-job.ts": { max: 3, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds before its LIMIT (n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
  "lib/stt/room-drain.ts": { max: 16, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds before its LIMIT (n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
  "lib/transcript/repeat-runs-backfill.ts": { max: 3, why: "production pipeline CHOOSER: picks its own windows, leaves held-out ones out through room-access blindWindowIds, filtering the scan result in JS before it ranks/caps (no SQL LIMIT; exact n_blind_excluded); still names bench_window/room_diarize_window in its own scan" },
};
