#!/usr/bin/env node
/**
 * Regenerate content/buglog-content.ts from a source ETA-BUG-LOG.md.
 *
 * The bug log's canonical home is the Daily Dash ETA folder (not reachable by
 * Vercel), so we embed a snapshot in the repo as a JS string module — robust
 * against Next.js file-tracing and never exposed as a public static file (the
 * /buglog page is auth-gated). Run this, commit, push → Vercel rebuilds /buglog.
 *
 * Usage: node scripts/sync-buglog.mjs <path-to-ETA-BUG-LOG.md>
 */
import { readFileSync, writeFileSync } from "node:fs";

const src = process.argv[2];
if (!src) { console.error("usage: node scripts/sync-buglog.mjs <path-to-ETA-BUG-LOG.md>"); process.exit(1); }
const md = readFileSync(src, "utf8");
const updated = new Date().toISOString();
const body =
  "// AUTO-GENERATED by scripts/sync-buglog.mjs — do not edit by hand.\n" +
  "// Snapshot of ETA-BUG-LOG.md, embedded as a string so the auth-gated\n" +
  "// /buglog page can render it without filesystem reads.\n" +
  `export const BUGLOG_MD = ${JSON.stringify(md)};\n` +
  `export const BUGLOG_UPDATED_AT = ${JSON.stringify(updated)};\n`;
writeFileSync("content/buglog-content.ts", body);
console.log(`wrote content/buglog-content.ts (${md.length} chars, updated ${updated})`);
