/**
 * number-words-indic.test.ts — Tamil, Telugu, Malayalam, Marathi, Bengali and Gujarati number words are exempt
 * from the loop collapse, exactly as English, Hindi and Kannada already were.
 *
 * WHY: the production STT router stops forcing English, so these languages arrive in native script. A repeated
 * number word is a regimen read aloud ("1-1-1"), and collapsing it to one copy can change a dose. The exemption
 * list is lib/stt/number-words.json, generated by scripts/sync-number-words.mjs from the router-generated base
 * (number-words.base.json, 772 words, untouched) plus the shared Indic lexicon (eta-lab shared/number-words-indic-v1.json,
 * also consumed by the router). All text here is synthetic.
 *
 * Both collapse modules are covered — assembled-collapse (assembled text, Indic engine output) and
 * hallucination-collapse (the router-rule port) — because each loads the same JSON independently.
 */
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { collapseAssembled, collapseLine, isNumberToken, joinAndCollapse } from "@/lib/stt/assembled-collapse";
import { collapsePhraseLoops, isNumberToken as isNumberTokenH } from "@/lib/stt/hallucination-collapse";

type Lexicon = { words: string[]; count: number; base_count?: number; lexicon_sha256: string };
const lexicon = JSON.parse(readFileSync("lib/stt/number-words.json", "utf8")) as Lexicon;
const base = JSON.parse(readFileSync("lib/stt/number-words.base.json", "utf8")) as Lexicon;

const SHARED_PATH = process.env.NUMBER_WORDS_SHARED || join(homedir(), "dev/eta-lab/shared/number-words-indic-v1.json");
const sharedPresent = existsSync(SHARED_PATH);
if (!sharedPresent) console.info(`number-words-indic: parity test skipped — ${SHARED_PATH} not present (set NUMBER_WORDS_SHARED)`);

describe("the merged lexicon file", () => {
  it("keeps the 772 router-generated base words, untouched", () => {
    expect(base.words).toHaveLength(772);
    expect(base.lexicon_sha256).toBe("08ffdfde64ecc886");
    const have = new Set(lexicon.words);
    expect(base.words.filter((w) => !have.has(w))).toEqual([]);
    expect(lexicon.base_count).toBe(772);
    expect(lexicon.count).toBeGreaterThan(772);
  });

  it("every entry is NFC, non-empty, trimmed, whitespace-free and unique", () => {
    const seen = new Set<string>();
    for (const w of lexicon.words) {
      expect(w.length, "empty entry").toBeGreaterThan(0);
      expect(w, `not NFC: ${JSON.stringify(w)}`).toBe(w.normalize("NFC"));
      expect(w, `not trimmed: ${JSON.stringify(w)}`).toBe(w.trim());
      expect(/\s/u.test(w), `whitespace in ${JSON.stringify(w)} (matcher is single-token)`).toBe(false);
      expect(seen.has(w), `duplicate ${w}`).toBe(false);
      seen.add(w);
    }
    expect(seen.size).toBe(lexicon.count);
  });

  const parity = sharedPresent ? it : it.skip;
  parity("parity: every entry of the shared Indic lexicon is in lib/stt/number-words.json", () => {
    const shared = JSON.parse(readFileSync(SHARED_PATH, "utf8")) as { languages: string[]; entries: Record<string, string[]> };
    expect(shared.languages).toEqual(["ta", "te", "ml", "mr", "bn", "gu"]);
    const have = new Set(lexicon.words);
    for (const lang of shared.languages) {
      const list = shared.entries[lang]!;
      expect(list.length, lang).toBeGreaterThan(50);
      expect(list.filter((w) => !have.has(w)), `${lang}: shared entries missing from number-words.json (run scripts/sync-number-words.mjs)`).toEqual([]);
      for (const w of list) {
        expect(w, `${lang}: not NFC ${JSON.stringify(w)}`).toBe(w.normalize("NFC"));
        expect(/[A-Za-z]/.test(w), `${lang}: Latin letter in ${JSON.stringify(w)}`).toBe(false);
      }
    }
  });
});

describe("the lexicon knows the new languages' numbers", () => {
  // cardinals, tens, hundreds, fractions and fused compounds, one or more per language
  const KNOWN = [
    "ஒன்று", "ரெண்டு", "இருபத்தொன்று", "இருபது", "நூறு", "அரை", "ஒன்றரை", // ta
    "ఒకటి", "రెండు", "ఇరవై", "వంద", "అర", "ఒకటిన్నర",                       // te
    "ഒന്ന്", "ഒന്നു", "ഇരുപത്തിയൊന്ന്", "നൂറ്", "അര", "ഒന്നര",                // ml
    "दोन", "एकवीस", "शंभर", "दीड", "अडीच", "साडेतीन",                         // mr
    "এক", "দুই", "একুশ", "একশো", "দেড়", "আড়াই", "সাড়ে",                    // bn
    "એક", "બે", "એકવીસ", "સો", "દોઢ", "અઢી", "સાડા",                         // gu
    "௧", "౧", "൧", "१", "১", "૧",                                            // one in each script's digits
  ];
  it("both modules recognise each one", () => {
    for (const w of KNOWN) {
      expect(isNumberToken(w), `assembled: ${w}`).toBe(true);
      expect(isNumberTokenH(w), `hallucination: ${w}`).toBe(true);
    }
  });
  it("and not ordinary words in those scripts", () => {
    for (const w of ["நன்றி", "ధన్యవాదాలు", "നന്ദി", "धन्यवाद", "ধন্যবাদ", "આભાર", "மாத்திரை", "మాత్ర", "ഗുളിക"]) {
      expect(isNumberToken(w), `assembled: ${w}`).toBe(false);
      expect(isNumberTokenH(w), `hallucination: ${w}`).toBe(false);
    }
  });
});

// A "1-1-1" regimen spoken as three identical number words, and three identical numbers in a dose phrase.
const REGIMENS: Array<[string, string]> = [
  ["ta", "ஒன்று"],
  ["ta colloquial", "ஒண்ணு"],
  ["te", "ఒకటి"],
  ["ml", "ഒന്ന്"],
  ["ml -u ending", "ഒന്നു"],
  ["mr", "दोन"],
  ["bn", "দুই"],
  ["gu", "એક"],
  ["gu fraction", "દોઢ"],
];
// A word that is not a number, repeated: a real loop, collapsed as before.
const LOOP_WORDS: Array<[string, string]> = [
  ["ta", "நன்றி"],
  ["te", "ధన్యవాదాలు"],
  ["ml", "നന്ദി"],
];

describe("a repeated number word in a new language is NOT collapsed (a regimen, not a loop)", () => {
  for (const [lang, w] of REGIMENS) {
    const three = `${w} ${w} ${w}`;
    it(`${lang}: "${three}" survives every entry point of assembled-collapse`, () => {
      expect(collapseLine(three)).toBe(three);
      const r = collapseAssembled(three);
      expect(r.text).toBe(three);
      expect(r.changed).toBe(false);
      expect(joinAndCollapse([w, w, w]).text).toBe(three);
      expect(collapseAssembled(`${w}\n${w}\n${w}`).text).toBe(`${w}\n${w}\n${w}`);
    });
    it(`${lang}: "${three}" survives hallucination-collapse`, () => {
      expect(collapsePhraseLoops(three)).toBe(three);
    });
  }

  it("a phrase of number words repeated three times survives too (Telugu 'ఇరవై ఒకటి' twenty-one, Tamil fused)", () => {
    const te = "ఇరవై ఒకటి ఇరవై ఒకటి ఇరవై ఒకటి";
    expect(collapseLine(te)).toBe(te);
    expect(collapsePhraseLoops(te)).toBe(te);
    const ta = "இருபத்தொன்று இருபத்தொன்று இருபத்தொன்று";
    expect(collapseLine(ta)).toBe(ta);
    expect(collapsePhraseLoops(ta)).toBe(ta);
  });
});

describe("a genuine loop in those languages is still collapsed", () => {
  // Six identical words do not collapse to ONE: the collapse tries the longest unit first, so "w w w w w w" is a
  // 2-word unit repeated 3 times and keeps "w w". That is the existing behaviour, unchanged here; the control is the
  // same loop in Latin script, which must come out the same shape.
  const six = (w: string) => Array(6).fill(w).join(" ");
  const CONTROL = "thanks";
  for (const [lang, w] of LOOP_WORDS) {
    it(`${lang}: "${w}" x3 collapses to one, x6 collapses exactly as the Latin control does, in both modules`, () => {
      expect(isNumberToken(w)).toBe(false);
      expect(isNumberTokenH(w)).toBe(false);
      const three = `${w} ${w} ${w}`;
      expect(collapseLine(three)).toBe(w);
      expect(collapseAssembled(three).text).toBe(w);
      expect(collapsePhraseLoops(three)).toBe(w);
      const shape = (fn: (t: string) => string) => fn(six(w)).split(" ").length;
      expect(shape(collapseLine)).toBe(collapseLine(six(CONTROL)).split(" ").length);
      expect(shape(collapseLine)).toBeLessThan(6);
      expect(shape((t) => collapseAssembled(t).text)).toBe(collapseAssembled(six(CONTROL)).text.split(" ").length);
      expect(shape(collapsePhraseLoops)).toBe(collapsePhraseLoops(six(CONTROL)).split(" ").length);
      expect(shape(collapsePhraseLoops)).toBeLessThan(6);
      expect(joinAndCollapse(Array(3).fill(w)).text).toBe(w);
    });
  }
  it("a two-word Tamil loop collapses, with a dose phrase beside it left alone", () => {
    const loop = Array(4).fill("நன்றி டாக்டர்").join(" ");
    expect(collapsePhraseLoops(loop)).toBe("நன்றி டாக்டர்");
    const dose = "ஒன்று ஒன்று ஒன்று";
    expect(collapseAssembled(`${loop}\n${dose}`).text).toBe(`நன்றி டாக்டர்\n${dose}`);
  });
});

describe("the existing English, Hindi and Kannada exemptions still hold", () => {
  const CASES = ["one one one", "दो दो दो", "पचास पचास पचास", "ಕಾಲು ಕಾಲು ಕಾಲು", "ಒಂದು ಒಂದು ಒಂದು", "pachas pachas pachas"];
  for (const c of CASES) {
    it(`"${c}" is not collapsed`, () => {
      expect(collapseLine(c)).toBe(c);
      expect(collapsePhraseLoops(c)).toBe(c);
    });
  }
  it("and a plain English or Hindi loop still is", () => {
    expect(collapseLine("accha accha accha")).toBe("accha");
    expect(collapsePhraseLoops("accha accha accha")).toBe("accha");
    expect(collapseLine("बुखार बुखार बुखार")).toBe("बुखार");
  });
});

describe("precomposed engine output matches the NFC lexicon (the matcher normalises the token)", () => {
  // Written by code point: each is the PRECOMPOSED form an engine may emit, which NFC decomposes.
  const BN_CHHOY = "\u099B\u09DF";                 // ছয় (6) with য় as U+09DF
  const BN_DER = "\u09A6\u09C7\u09DC";            // দেড় (1.5) with ড় as U+09DC
  const HI_HAZAR = "\u0939\u095B\u093E\u0930";    // हज़ार (thousand) with ज़ as U+095B — a Hindi base word
  const HI_DEDH = "\u0921\u0947\u095D";           // डेढ़ (1.5) with ढ़ as U+095D — a Hindi base word
  const CASES: Array<[string, string]> = [["bn ছয়", BN_CHHOY], ["bn দেড়", BN_DER], ["hi hazar", HI_HAZAR], ["hi डेढ़", HI_DEDH]];
  const words = new Set(lexicon.words);
  for (const [label, w] of CASES) {
    it(`${label}: precomposed form is not in the list as-is, but both modules treat it as a number`, () => {
      expect(w).not.toBe(w.normalize("NFC"));
      expect(words.has(w), "lexicon must stay NFC").toBe(false);
      expect(words.has(w.normalize("NFC"))).toBe(true);
      expect(isNumberToken(w)).toBe(true);
      expect(isNumberTokenH(w)).toBe(true);
      const three = `${w} ${w} ${w}`;
      expect(collapseLine(three)).toBe(three);
      expect(collapsePhraseLoops(three)).toBe(three);
    });
  }
  it("a joined regimen token with a precomposed part is a number too", () => {
    expect(isNumberToken(`${BN_CHHOY}-${BN_CHHOY}`)).toBe(true);
    expect(isNumberTokenH(`${BN_DER}/${BN_DER}`)).toBe(true);
  });
  it("and a precomposed non-number still is not", () => {
    const w = "\u09A1\u09BC\u09BE\u0995"; // not a number word
    expect(isNumberToken(w)).toBe(false);
    expect(isNumberTokenH(w)).toBe(false);
  });
});

describe("v1.1 additions (Refuter omissions) are in the committed list", () => {
  const V11: Record<string, string> = {
    mr: "दीडशे अडीचशे साडेसहाशे एकशे",
    bn: "দেড়শো আড়াইশো কুড়ি",
    gu: "એકસો દોઢસો અઢીસો",
    te: "నూట ముప్ఫై", // two tokens in running text; each is its own entry
    ta: "பாதி முன்னூறு ஐநூறு இருநூற்று முன்னூற்று நானூற்று ஐநூற்று அறுநூற்று எழுநூற்று எண்ணூற்று தொள்ளாயிரத்து",
    ml: "എഴുന്നൂറ് നാൽപത് ഇരുന്നൂറ്റി മുന്നൂറ്റി നാനൂറ്റി അഞ്ഞൂറ്റി അറുനൂറ്റി എഴുനൂറ്റി എണ്ണൂറ്റി തൊള്ളായിരത്തി",
  };
  const have = new Set(lexicon.words);
  for (const [lang, list] of Object.entries(V11)) {
    it(`${lang}: every v1.1 entry is present (NFC) and exempt from collapse in both modules`, () => {
      for (const w of list.split(" ")) {
        const n = w.normalize("NFC");
        expect(have.has(n), `${lang}: ${w} missing`).toBe(true);
        expect(isNumberToken(w), `assembled ${w}`).toBe(true);
        expect(isNumberTokenH(w), `hallucination ${w}`).toBe(true);
        const three = `${w} ${w} ${w}`;
        expect(collapseLine(three)).toBe(three);
        expect(collapsePhraseLoops(three)).toBe(three);
      }
    });
  }
});
