/**
 * The served bootstrap script after the Linux port: ONE script, the platform decided on the machine by
 * `uname -s`, and the Mac branch held to the byte.
 *
 * ─── WHY THE MAC GOLDEN IS A LITERAL AND NOT A SNAPSHOT ─────────────────────────────────────
 * Nine rooms re-enrol by pasting this script. The golden below was written against the script as it was
 * served BEFORE the Linux branch existed, and this file was run green against that code before the Linux
 * branch was added. A snapshot file can be regenerated by a flag; a literal has to be edited by a person
 * who can see what they are changing.
 *
 * The Linux branch is a single `if [ "$(uname -s)" = "Linux" ]; then ... fi` block, rendered by its own
 * function. Remove exactly that block and what remains must equal the golden, byte for byte. bash reads a
 * whole compound command before it runs any of it, so on a Mac the block costs one `uname` and nothing
 * else — the second test proves that by RUNNING the script under bash with `uname` answering Darwin.
 */
import { describe, it, expect, vi } from "vitest";
import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, writeFileSync, chmodSync, readFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

vi.mock("@/lib/db", () => {
  const sql = () => Promise.resolve([]);
  (sql as unknown as { transaction: unknown }).transaction = async () => [];
  return { sql, db: {} };
});
vi.mock("@/lib/cookie", () => ({ readAdminCookie: async () => null }));
vi.mock("@/lib/auth", () => ({ verifyAdminJwt: async () => null }));

const M = await import("@/lib/room-install");

const MAC = {
  token: "0123456789abcdef0123456789abcdef",
  origin: "https://www.evenscribe.app",
  blobUrl: "https://x.public.blob.vercel-storage.com/rr-0.1.21.zip",
  sha256: "b".repeat(64),
  version: "0.1.21",
  roomName: "OPD 5",
};

/** The Mac script exactly as it was served before the Linux port. Do not edit to make a test pass. */
const MAC_GOLDEN = `#!/bin/bash
set -euo pipefail

APP="EvenScribe Room Recorder.app"
DEST="$HOME/Applications"
PLIST="$HOME/Library/LaunchAgents/com.evenscribe.room-recorder.plist"
TOKEN="0123456789abcdef0123456789abcdef"
ORIGIN="https://www.evenscribe.app"
BLOB_URL="https://x.public.blob.vercel-storage.com/rr-0.1.21.zip"
EXPECTED_SHA="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
TMP="$(mktemp -d)"

echo "Downloading EvenScribe Room Recorder 0.1.21..."
curl -fsSL -o "$TMP/app.zip" "$BLOB_URL"

echo "Verifying the download..."
ACTUAL_SHA="$(shasum -a 256 "$TMP/app.zip" | awk '{print $1}')"
if [ "$ACTUAL_SHA" != "$EXPECTED_SHA" ]; then
  echo "Checksum mismatch. Install stopped. Nothing was changed."
  exit 1
fi

echo "Stopping any earlier copy..."
launchctl bootout "gui/$(id -u)/com.evenscribe.room-recorder" 2>/dev/null || true

echo "Installing into ~/Applications..."
mkdir -p "$DEST"
ditto -x -k "$TMP/app.zip" "$TMP/expanded"
rm -rf "$DEST/$APP"
ditto "$TMP/expanded/$APP" "$DEST/$APP"

echo "Enrolling this Mac..."
"$DEST/$APP/Contents/MacOS/room-recorder" enrol --token "$TOKEN" --origin "$ORIGIN"

echo "Installing the LaunchAgent..."
"$DEST/$APP/Contents/MacOS/room-recorder" install-launch-agent

echo "Starting the app..."
launchctl bootstrap "gui/$(id -u)" "$PLIST" || launchctl load "$PLIST"

rm -rf "$TMP"
echo "Installed and enrolled as OPD 5. Close this window."
`;

/**
 * Everything the script renders, minus the Linux block. The block must sit IMMEDIATELY after the
 * script's second line: anywhere else, a Mac would run Mac lines before `uname` was asked.
 */
function macPart(script: string, linux: Parameters<typeof M.renderLinuxBranch>[0]["release"] = null): string {
  const head = "#!/bin/bash\nset -euo pipefail\n";
  const block = M.renderLinuxBranch({ token: MAC.token, origin: MAC.origin, release: linux });
  expect(script.startsWith(head + block)).toBe(true);
  return head + script.slice(head.length + block.length);
}

/**
 * Run a rendered script the way the paste does — piped into `bash` on stdin — in a sandbox whose PATH
 * starts with stubs. Every stub appends its name and argv to `calls.log`, so a test can say what ran.
 */
function runPiped(script: string, stubs: Record<string, string>, env: Record<string, string> = {}) {
  const dir = mkdtempSync(join(tmpdir(), "rr-bootstrap-"));
  const bin = join(dir, "bin");
  mkdirSync(bin);
  const log = join(dir, "calls.log");
  writeFileSync(log, "");
  for (const [name, body] of Object.entries(stubs)) {
    const p = join(bin, name);
    writeFileSync(p, `#!/bin/bash\nprintf '%s\\n' "${name} $*" >> "${log}"\n${body}\n`);
    chmodSync(p, 0o755);
  }
  const res = spawnSync("bash", [], {
    input: script,
    encoding: "utf8",
    // A clean environment on purpose — nothing of the test runner's leaks into the script under test.
    env: { PATH: `${bin}:/usr/bin:/bin:/usr/sbin:/sbin`, HOME: dir, TMPDIR: dir, ...env } as unknown as NodeJS.ProcessEnv,
  });
  return { dir, status: res.status, out: `${res.stdout}${res.stderr}`, calls: readFileSync(log, "utf8") };
}

describe("the Mac branch of the served script", () => {
  it("is byte for byte the script served before the Linux port", () => {
    expect(macPart(M.renderBootstrapScript(MAC))).toBe(MAC_GOLDEN);
  });

  it("parses as bash", () => {
    execFileSync("bash", ["-n"], { input: M.renderBootstrapScript(MAC) });
  });

  it("on Darwin, runs the Mac body and nothing of the Linux branch", () => {
    // curl fails the download, so the Mac body stops at its first network step having proved it got there.
    const r = runPiped(M.renderBootstrapScript(MAC), { uname: 'echo Darwin', curl: "exit 22" });
    expect(r.out).toContain("Downloading EvenScribe Room Recorder 0.1.21...");
    expect(r.out).not.toContain("Linux");
    const lines = r.calls.split("\n").filter(Boolean);
    expect(lines).toHaveLength(2);
    expect(lines[0]).toBe("uname -s");
    expect(lines[1]).toMatch(new RegExp(`^curl -fsSL -o \\S+/app\\.zip ${MAC.blobUrl.replace(/[.]/g, "\\.")}$`));
    expect(r.status).toBe(22);
  });
});

describe("the Linux branch of the served script", () => {
  it("with no Linux release published, stops on Linux before touching anything", () => {
    const r = runPiped(M.renderBootstrapScript(MAC, null), { uname: 'echo Linux', curl: "exit 0", sudo: "exit 0" });
    expect(r.status).toBe(1);
    expect(r.out).toContain("not yet published for Linux. Nothing was changed.");
    expect(r.calls.split("\n").filter(Boolean)).toEqual(["uname -s"]);
  });
});
